spring.application.name=atividade

Lembrando que você deve modificar isso aqui dependendo do contexto do seu projeto, ex: você não usa MySQLDialect no postgres.

# ==============================

# CONFIGURAÇÃO DO SERVIDOR

# ==============================

server.port=8080


# ==============================

# CONFIGURAÇÃO DO BANCO DE DADOS (MySQL)

# ==============================

spring.datasource.url=jdbc:mysql://localhost:3306/atv1?useSSL=false&serverTimezone=UTC

spring.datasource.username=root

spring.datasource.password=mysqlPW

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==============================

# CONFIGURAÇÃO DO JPA / HIBERNATE

# ==============================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# ==============================

# CONFIGURAÇÃO EXTRA (LOGS)

# ==============================

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==============================